export { default as Navbar } from "./Navbar";
export { default as Main } from "./Main";
export { default as Achievments } from "./Achievments";
export { default as Features } from "./Features";
export { default as Bill } from "./Bill";
export { default as Card } from "./Card";
export { default as Quotes } from "./Quotes";
export { default as Service } from "./Service";
export { default as Footer } from "./Footer";
